-- Contractor directory data (BUILD-everything.md step 3). Loaded from
-- content/data/enriched.json (scripts/enrich-contractors.py output) via
-- scripts/load-contractors.js. Reviews are NOT stored here — those are
-- fetched live and cached separately in places_cache (step 4).
create table if not exists public.contractors (
  id bigint generated by default as identity primary key,
  place_id text unique,
  name text not null,
  website text,
  city text,
  state text,
  phones jsonb not null default '[]',
  emails jsonb not null default '[]',
  services jsonb not null default '[]',
  raw_services jsonb not null default '[]',
  service_areas jsonb not null default '[]',
  trust_signals jsonb not null default '{}',
  socials jsonb not null default '{}',
  has_photo_gallery boolean not null default false,
  has_contact_form boolean not null default false,
  title text,
  meta_description text,
  status text not null default 'ok',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists contractors_state_idx on public.contractors (state);
create index if not exists contractors_city_idx on public.contractors (city);

alter table public.contractors enable row level security;

-- No policies: this table is loaded and read by build-time/service-role
-- scripts only (the static site reads content/data/enriched.json directly
-- at build time). No public client-side access needed yet.
